pipeline_name: dd

# env
env_name: can
env_type: ph
abs_action: false

datapath: /nethome/yzhang4179/flash/robomimic/datasets/lift/ph/image.hdf5
# datapath: /home/yixin/Downloads/robomimic_low_dim/datasets/lift/mh/low_dim.hdf5
#datapath: /home/yixin/Downloads/robomimic/datasets/lift/ph/image.hdf5
mode: train
max_episode_steps: 400
render_obs_key: 'agentview_image'
shape_meta:
  action:
    'action'
  agentview_image:
    'RGB'
  robot0_eye_in_hand_image:
    'RGB'

action_dim: 7
obs_steps: 1
action_steps: 1

agent_model_path: /nethome/yzhang4179/flash/diffuser_mujoco/bc_img_scriptsv3/results/bc/model_latest
# train
device: cuda:0
seed: 0
horizon: 16

solver: ddpm
temperature: 0.5
use_ema: true




# eval
model_path: /home/yixin/Desktop/false_3
num_envs: 1
eval_episodes: 50
save_video: true
eval_freq: 100000

# log
exp_name: lift
save_path: results
project: latent_diffuser
group: latent_diffuser
wandb_mode: online
log_freq: 1000
save_freq: 50000

# hydra
hydra:
  run:
    dir: results/${project}/
  job:
    chdir: false



