pipeline_name: dd

# env
env_name: can
env_type: ph
abs_action: false

#datapath: /nethome/yzhang4179/flash/robomimic/datasets/lift/ph/image.hdf5
# datapath: /home/yixin/Downloads/robomimic_low_dim/datasets/lift/mh/low_dim.hdf5
datapath: /home/yixin/Downloads/robomimic/datasets/lift/ph/image.hdf5
mode: train
max_episode_steps: 400
render_obs_key: 'agentview_image'
shape_meta:
  action:
    'action'
  agentview_image:
    'RGB'

action_dim: 7
obs_steps: 1
action_steps: 1

agent_model_path: /nethome/yzhang4179/flash/diffuser_mujoco/bc_img_scriptsv3/results/bc/model_latest
# train
device: cuda:0
seed: 0
gradient_steps: 1000000
batch_size: 256

dreamer_horizon: 2 # dreamer horizon at least 2
diffuser_horizon: 8

solver: ddpm
temperature: 0.5
use_ema: true
# optimizer
lr: 0.0001
diffusion_gradient_steps: 1000000
invdyn_gradient_steps: 1000000

# Dreamer
latent_size: 256
hidden_size: 512
belief_size: 200
state_size: 30
# Dit
emb_dim: 256  # 160
d_model: 1200
n_heads: 25
depth: 7
label_dropout: 0.25
sampling_steps: 100
predict_noise: True
next_obs_loss_weight: 10.
ema_rate: 0.9999

# eval
model_path: /home/yixin/Desktop/false_3
num_envs: 1
eval_episodes: 50
save_video: true
eval_freq: 100000

# log
exp_name: lift
save_path: results
project: diffuserv3
group: diffuser
wandb_mode: online
log_freq: 1000
save_freq: 100000

# hydra
hydra:
  run:
    dir: results/${project}/
  job:
    chdir: false



